name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # instala desde requirements si existe, y asegura pyinstaller
          if (Test-Path requirements.txt) { pip install -r requirements.txt } else { pip install pyinstaller iqoptionapi python-dotenv pandas }
          pip install pyinstaller --upgrade

      - name: Show repository files (debug)
        run: |
          echo "LISTING ROOT"
          dir
          echo "---- show main.py head ----"
          Get-Content main.py -TotalCount 40

      - name: Build executable (PyInstaller)
        run: |
          pyinstaller --onefile --collect-all dotenv --hidden-import connector --hidden-import dotenv --add-data "connector.py;." --add-data "strategy.py;." --add-data "manager.py;." --add-data ".env;." main.py

      - name: Show dist folder (debug)
        run: |
          echo "DIST CONTENTS:"
          dir dist

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: IQBot-Windows
          path: dist/main.exe
