name: Build Windows EXE
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller iqoptionapi websocket-client requests

      - name: Build exe (force include all)
        run: |
          pyinstaller --onefile main.py ^
          --hidden-import=iqoptionapi ^
          --hidden-import=iqoptionapi.stable_api ^
          --hidden-import=websocket ^
          --hidden-import=requests ^
          --hidden-import=json ^
          --hidden-import=time ^
          --hidden-import=datetime ^
          --clean

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iq-bot-exe
          path: dist/main.exe
