name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller iqoptionapi python-dotenv

      - name: Build executable including all needed files
        run: |
          pyinstaller --onefile ^
            --add-data "connector.py;." ^
            --add-data ".env;." ^
            --hidden-import dotenv ^
            main.py

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: IQBot-Windows
          path: dist/main.exe
